name: 编译内核A14-6.1

permissions:
  contents: write
  actions: write
  
on:
  workflow_dispatch:
    inputs:
      kernelsu_variant:
        description: "选择 KernelSU"
        required: true
        type: choice
        options:
          - Official
          - Next
          - MKSU
          - SukiSU
        default: SukiSU
      kernelsu_branch:
        description: "选择 KSU 分支"
        required: true
        type: choice
        options:
          - "Stable(标准)"
          - "Dev(开发)"
          - "Other(其他/指定)"
        default: "Dev(开发)"
      sukisu_branch:
        description: "选择 SukiSU 分支"
        required: true
        type: choice
        options:
          - "builtin"
          - "tmp-builtin"
        default: "builtin"
      version:
        description: "自定义版本名"
        required: true
        type: string
        default: "-android14-11-gca0ef6d17716-ab13624819"
      build_time:
        description: "设置内核构建时间"
        required: true
        type: string
        default: "Tue Jun 10 18:59:08 UTC 2025"
      lz4_upd:
        description: "lz4 1.10.0"
        required: true
        type: boolean
        default: true
      ssg_io:
        description: "三星SSG I/O调度器"
        required: true
        type: boolean
        default: true
      rekernel_enable:
        description: "Re:Kernel支持"
        required: true
        type: boolean
        default: true
      BBG:
        description: "Baseband-guard支持"
        required: false
        type: boolean
        default: false
      kpm_enable:
        description: "KPM支持"
        required: false
        type: boolean
        default: false

jobs:
  build-kernel-a14-6-1:
    uses: ./.github/workflows/Kernel-A14-6.1.yml
    secrets: inherit
    with:
      make_release: false
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      sukisu_branch: ${{ inputs.sukisu_branch }}
      version: ${{ inputs.version }}
      build_time: ${{ inputs.build_time }}
      lz4_upd: ${{ inputs.lz4_upd }}
      ssg_io: ${{ inputs.ssg_io }}
      rekernel_enable: ${{ inputs.rekernel_enable }}
      BBG: ${{ inputs.BBG }}
      kpm_enable: ${{ inputs.kpm_enable }}
