name: Android 14 6.1
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_call:  # This allows this workflow to be called from another workflow
    inputs:
      make_release:
        required: true
        type: boolean
        default: true
      kernelsu_variant:
        required: true
        type: string
        default: Next
      kernelsu_branch:
        required: true
        type: string
        default: Dev
      sukisu_branch:
        required: true
        type: string
        default: builtin
      version:
        description: "自定义版本名"
        required: true
        type: string
        default: "-android14-11-gca0ef6d17716-ab13624819"
      build_time:
        description: '设置内核构建时间'
        required: true
        type: string
        default: "Tue Jun 10 18:59:08 UTC 2025"
      lz4_upd:
        description: 'lz4 1.10.0'
        required: true
        type: boolean
        default: true
      ssg_io:
        description: '三星SSG I/O调度器'
        required: true
        type: boolean
        default: true
      rekernel_enable:
        description: 'Re:Kernel支持'
        required: true
        type: boolean
        default: true
      BBG:
        description: 'Baseband-guard支持'
        required: false
        type: boolean
        default: false
      kpm_enable:
        description: 'KPM支持'
        required: false
        type: boolean
        default: false
        
jobs:
  build-kernel-a14-6-1-kernelsu-susfs:
    strategy:
      fail-fast: false
      matrix:
        include:
          - sub_level: "118"
            os_patch_level: "2025-01"
    uses: ./.github/workflows/GKI-Kernel.yml
    secrets: inherit
    with:
      make_release: ${{ inputs.make_release }}
      android_version: "android14"
      kernel_version: "6.1"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      sukisu_branch: ${{ inputs.sukisu_branch }}
      version: ${{ inputs.version }}
      build_time: ${{ inputs.build_time }}
      lz4_upd: ${{ inputs.lz4_upd }}
      ssg_io: ${{ inputs.ssg_io }}
      rekernel_enable: ${{ inputs.rekernel_enable }}
      BBG: ${{ inputs.BBG }}
      kpm_enable: ${{ inputs.kpm_enable }}
