name: Android 14 6.1
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_call:  # This allows this workflow to be called from another workflow
    inputs:
      make_release:
        required: true
        type: boolean
        default: true
      kernelsu_variant:
        required: true
        type: string
        default: Next
      kernelsu_branch:
        required: true
        type: string
        default: Dev
      version:
        required: true
        type: string
        default: "-android14-11-gca0ef6d17716-ab13624819"
      ssg_lz4_upd:
        description: '三星SSG IO调度器 && LZ4 1.10.0'
        required: true
        type: boolean
        default: true
      BBG:
        description: '启用BBG防格机补丁'
        required: true
        type: boolean
        default: true
      set_defbbr:
        description: '将BBR设为默认拥塞算法'
        required: true
        type: boolean
        default: true
      rekernel_enable:
        description: '添加Re:Kernel支持'
        required: true
        type: boolean
        default: true
      build_time:
        description: '设置内核构建时间(格式见仓库说明)'
        required: true
        type: string
        default: "Tue Jun 10 18:59:08 UTC 2025"
      use_O3:
        description: '开启O3编译优化'
        required: true
        type: boolean
        default: true
      more_zram_kpm:
        description: '启用更多ZRAM算法 & & KPM功能'
        required: false
        type: boolean
        default: false
        
jobs:
  build-kernel-a14-6-1-kernelsu-susfs:
    strategy:
      fail-fast: false
      matrix:
        include:
          - sub_level: "118"
            os_patch_level: "2025-01"
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      make_release: ${{ inputs.make_release || false }}
      android_version: "android14"
      kernel_version: "6.1"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      kernelsu_variant: ${{ inputs.kernelsu_variant || 'Next' }}
      kernelsu_branch: ${{ inputs.kernelsu_branch || 'Dev' }}
      version: ${{ inputs.version }}
      ssg_lz4_upd: ${{ inputs.ssg_lz4_upd }}
      BBG: ${{ inputs.BBG }}
      set_defbbr: ${{ inputs.set_defbbr }}
      rekernel_enable: ${{ inputs.rekernel_enable }}
      build_time: ${{ inputs.build_time }}
      use_O3: ${{ inputs.use_O3 || false }}
      more_zram_kpm: ${{ inputs.more_zram_kpm }}
